version: "3"
services:
  nginx:
    image: jhonoryza/nginx:laravel-alpine
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./mydocker/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf
      - ./mydocker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"

  fpm:
    image: jhonoryza/php:ubuntu-7.4-swoole
    working_dir: /var/www/html
    #user: "1001"
    volumes:
      - ./src:/var/www/html
    ports:
      - "1215:1215" # Swoole port
    command: bash -c "php artisan swoole:http start" # Uncomment this if your use Swoole.
