name: 'Build php docker image for laravel swoole'

on:
    watch:
        types: [started]
    #push:
    #    branches:
    #        - master

jobs:
    release:
        runs-on: ubuntu-latest
        
        #permission only owner can trigger
        if: github.actor == github.event.repository.owner.login
        
        steps:
        -
            name: Checkout
            uses: actions/checkout@v1
        -
            name: Dockerhub login
            env:
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            run: |
                echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
        -
            name: Set up Docker Buildx
            id: buildx
            uses: crazy-max/ghaction-docker-buildx@v1
            with:
                version: latest
        -
            name: Build dockerfile (with push)
            run: |
                docker buildx build \
                --platform=linux/amd64,linux/arm/v7 \
                --output "type=image,push=true" \
                --file ./mydocker/php-fpm/Dockerfile . \
                --tag jhonoryza/php:ubuntu-7.4-swoole
